-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Creato il: Ago 16, 2024 alle 12:39
-- Versione del server: 8.0.32
-- Versione PHP: 8.0.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `my_vittoriopiotti`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `GestioneHotels_Rooms`
--

CREATE TABLE `GestioneHotels_Rooms` (
  `Id` int NOT NULL,
  `Name` varchar(24) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `Image` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `Description` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `Number` int DEFAULT NULL,
  `Cost` int DEFAULT NULL,
  `IdHotel` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Dump dei dati per la tabella `GestioneHotels_Rooms`
--

INSERT INTO `GestioneHotels_Rooms` (`Id`, `Name`, `Image`, `Description`, `Number`, `Cost`, `IdHotel`) VALUES
(1, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 4),
(2, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 4),
(3, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 4),
(4, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 4),
(5, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 4),
(6, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 4),
(7, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 4),
(8, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 4),
(9, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 4),
(10, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 4),
(11, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 4),
(12, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 4),
(13, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 4),
(14, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 4),
(15, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 5),
(16, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 5),
(17, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 5),
(18, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 5),
(19, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 5),
(20, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 5),
(21, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 5),
(22, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 5),
(23, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 5),
(24, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 5),
(25, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 5),
(26, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 5),
(27, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 5),
(28, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 5),
(29, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 5),
(30, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 6),
(31, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 6),
(32, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 6),
(33, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 6),
(34, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 6),
(35, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 6),
(36, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 6),
(37, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 6),
(38, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 6),
(39, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 6),
(40, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 6),
(41, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 6),
(42, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 6),
(43, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 6),
(44, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 6),
(45, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 7),
(46, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 7),
(47, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 7),
(48, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 7),
(49, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 7),
(50, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 7),
(51, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 7),
(52, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 7),
(53, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 7),
(54, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 7),
(55, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 7),
(56, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 7),
(57, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 7),
(58, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 7),
(59, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 7),
(60, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 8),
(61, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 8),
(62, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 8),
(63, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 8),
(64, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 8),
(65, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 8),
(66, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 8),
(67, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 8),
(68, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 8),
(69, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 8),
(70, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 8),
(71, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 8),
(72, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 8),
(73, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 8),
(74, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 8),
(75, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 9),
(76, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 9),
(77, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 9),
(78, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 9),
(79, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 9),
(80, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 9),
(81, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 9),
(82, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 9),
(83, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 9),
(84, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 9),
(85, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 9),
(86, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 9),
(87, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 9),
(88, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 9),
(89, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 9),
(90, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 10),
(91, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 10),
(92, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 10),
(93, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 10),
(94, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 10),
(95, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 10),
(96, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 10),
(97, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 10),
(98, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 10),
(99, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 10),
(100, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 10),
(101, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 10),
(102, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 10),
(103, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 10),
(104, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 10),
(105, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 11),
(106, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 11),
(107, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 11),
(108, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 11),
(109, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 11),
(110, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 11),
(111, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 11),
(112, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 11),
(113, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 11),
(114, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 11),
(115, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 11),
(116, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 11),
(117, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 11),
(118, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 11),
(119, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 11),
(120, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 12),
(121, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 172, 150, 12),
(122, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 173, 300, 12),
(123, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 174, 100, 12),
(124, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 175, 150, 12),
(125, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 176, 300, 12),
(126, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 178, 100, 12),
(127, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 179, 150, 12),
(128, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 180, 300, 12),
(129, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 181, 100, 12),
(130, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 182, 150, 12),
(131, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 183, 300, 12),
(132, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 184, 100, 12),
(133, 'Stanza Matrimoniale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza2.png?raw=true', 'Una stanza matrimoniale elegante. Questa stanza matrimoniale è pensata per coppie in viaggio che desiderano un soggiorno romantico e confortevole.  ', 185, 150, 12),
(134, 'Suite Presidenziale', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza3.png?raw=true', 'Questa suite presidenziale è la scelta perfetta per coloro che cercano il massimo comfort e lusso durante il loro soggiorno. Con spazi ampi e arredi di lusso, questa suite offre una sistemazione di alto livello.', 186, 300, 12),
(135, 'Stanza Singola', 'https://github.com/vittorioPiotti/Gestione-Hotel-PHP/blob/main/project/Client/assets/images/stanza1.png?raw=true', 'Una stanza singola confortevole. Questa stanza singola è perfetta per chi viaggia da solo. Dotata di un comodo letto singolo, offre un ambiente accogliente e rilassante per il tuo soggiorno. ', 171, 100, 4),
(374, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 1, 150, 34),
(375, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 2, 150, 34),
(376, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 3, 150, 34),
(377, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 4, 150, 34),
(378, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 5, 150, 34),
(379, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 6, 150, 34),
(380, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 7, 150, 34),
(381, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 8, 150, 34),
(382, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 9, 150, 34),
(383, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 10, 150, 34),
(384, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 11, 150, 34),
(385, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 12, 150, 34),
(386, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 13, 150, 34),
(387, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 14, 150, 34),
(388, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 15, 150, 34),
(389, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 16, 150, 34);
INSERT INTO `GestioneHotels_Rooms` (`Id`, `Name`, `Image`, `Description`, `Number`, `Cost`, `IdHotel`) VALUES
(390, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 17, 150, 34),
(391, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 18, 150, 34),
(392, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 19, 150, 34),
(393, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 20, 150, 34),
(394, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 21, 150, 34),
(395, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 22, 150, 34),
(396, 'Nome Stanza', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihYeTXq5iZ1-tVn5U6e0SZqkj1naXzEWR1xXxPRzoLP4n0rC9PIOtqJRlEzrsrOktIi1FcPLFsYaP83Fgyj7mRKoTXhD-ZxBalA=w2880-h1626-rw-v1', 'Descrizione', 23, 150, 34),
(403, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 1, 150, 35),
(404, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 2, 150, 35),
(405, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 3, 150, 35),
(406, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 4, 150, 35),
(407, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 5, 150, 35),
(408, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 6, 150, 35),
(409, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 7, 150, 35),
(410, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 8, 150, 35),
(411, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 9, 150, 35),
(412, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 10, 150, 35),
(413, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 11, 150, 35),
(414, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 12, 150, 35),
(415, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 13, 150, 35),
(416, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 14, 150, 35),
(417, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 15, 150, 35),
(418, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 16, 150, 35),
(419, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 17, 150, 35),
(420, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 18, 150, 35),
(421, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 19, 150, 35),
(422, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 20, 150, 35),
(423, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 21, 150, 35),
(424, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 22, 150, 35),
(425, 'Nome Stanza1', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 23, 150, 35),
(426, 'Nome Stanza2', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 1, 330, 35),
(427, 'Nome Stanza2', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 2, 330, 35),
(428, 'Nome Stanza2', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 3, 330, 35),
(429, 'Nome Stanza2', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 4, 330, 35),
(430, 'Nome Stanza2', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihaB4OwmNBZ5lMqll4__cq-_41VxLPK3HDQgUEMj45AL8yU6RsiKFkrfYkFRjce4tFQ1z8QMvIQ1149P6zeqLCzrdLR_xJX_NVc=w2880-h1626-rw-v1', 'Descrizione', 5, 330, 35),
(477, 'Stanza Franca', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihZDPVNPJ7velxUXoTewqm0ruMDORfdBm7D1tTKDUZC9QfIyRZUbDurweUdjsh3UGlCKMxMsAFlzVPt2RzLAmm6xiza0H6YEdTA=w2880-h1626-rw-v1', 'Descrizione Stanza', 1, 330, 36),
(478, 'Stanza Franca', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihZDPVNPJ7velxUXoTewqm0ruMDORfdBm7D1tTKDUZC9QfIyRZUbDurweUdjsh3UGlCKMxMsAFlzVPt2RzLAmm6xiza0H6YEdTA=w2880-h1626-rw-v1', 'Descrizione Stanza', 2, 330, 36),
(479, 'Stanza Franca', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihZDPVNPJ7velxUXoTewqm0ruMDORfdBm7D1tTKDUZC9QfIyRZUbDurweUdjsh3UGlCKMxMsAFlzVPt2RzLAmm6xiza0H6YEdTA=w2880-h1626-rw-v1', 'Descrizione Stanza', 3, 330, 36),
(480, 'Stanza Franca', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihZDPVNPJ7velxUXoTewqm0ruMDORfdBm7D1tTKDUZC9QfIyRZUbDurweUdjsh3UGlCKMxMsAFlzVPt2RzLAmm6xiza0H6YEdTA=w2880-h1626-rw-v1', 'Descrizione Stanza', 4, 330, 36),
(481, 'Stanza Franca', 'https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihZDPVNPJ7velxUXoTewqm0ruMDORfdBm7D1tTKDUZC9QfIyRZUbDurweUdjsh3UGlCKMxMsAFlzVPt2RzLAmm6xiza0H6YEdTA=w2880-h1626-rw-v1', 'Descrizione Stanza', 5, 330, 36);

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `GestioneHotels_Rooms`
--
ALTER TABLE `GestioneHotels_Rooms`
  ADD PRIMARY KEY (`Id`),
  ADD KEY `FK_IdHotel` (`IdHotel`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT per la tabella `GestioneHotels_Rooms`
--
ALTER TABLE `GestioneHotels_Rooms`
  MODIFY `Id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=482;

--
-- Limiti per le tabelle scaricate
--

--
-- Limiti per la tabella `GestioneHotels_Rooms`
--
ALTER TABLE `GestioneHotels_Rooms`
  ADD CONSTRAINT `FK_IdHotel` FOREIGN KEY (`IdHotel`) REFERENCES `GestioneHotels_Hotels` (`Id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
